Class Recon : Doomplayer
{
    Default {
        Player.startitem "Milso";
        Player.startitem "SmokeGrenadeHand";
        Player.startitem "SmokeGrenade", 5;
        Player.startitem "MilsoAmmo", 5;
        Player.startitem "MilsoAmmoLoaded", 12;
        Player.startitem "RT_ThermopticCamo_Recon", 1;
        Player.DisplayName "Recon";
        Player.ForwardMove 1, 1;
        Player.SideMove 1, 1;
        Player.ViewBob 0.4;
        Player.JumpZ 10;
    }
}