Class Support : Doomplayer
{
    Default {
        Player.startitem "Milso";
        Player.startitem "SmokeGrenadeHand";
        Player.startitem "SmokeGrenade", 5;
        Player.startitem "MilsoAmmo", 5;
        Player.startitem "MilsoAmmoLoaded", 12;
        Player.DisplayName "Support";
        Player.ForwardMove 0.4, 0.2;
        Player.SideMove 0.4, 0.2;
        Player.ViewBob 0.2;
        Player.JumpZ 6;
    }
}